'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



'INSTANT C# NOTE: Formerly VB.NET project-level imports:

Imports Microsoft.VisualBasic
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Data
Imports System.Drawing
Imports System.Diagnostics
Imports System.Windows.Forms
Imports System.Linq
Imports System.Xml.Linq

Namespace libwmp3x_player
	Namespace My

		'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
		' or if you encounter build errors in this file, go to the Project Designer
		' (go to Project Properties or double-click the My Project node in
		' Solution Explorer), and make changes on the Application tab.
		'
		Partial Friend Class MyApplication
			Inherits Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase

			<Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
			Public Sub New()
				MyBase.New(Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
				Me.IsSingleInstance = False
				Me.EnableVisualStyles = True
				Me.SaveMySettingsOnExit = True
				Me.ShutdownStyle = Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
			End Sub

			<Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
			Protected Overrides Sub OnCreateMainForm()
				Me.MainForm = New Global.libwmp3x_player.Form1()
			End Sub

			Private Shared MyApp As MyApplication
			Friend Shared ReadOnly Property Application() As MyApplication
				Get
					Return MyApp
				End Get
			End Property

			<STAThread> _
			Shared Sub Main(ByVal args() As String)
				System.Windows.Forms.Application.SetCompatibleTextRenderingDefault(False)
				MyApp = New MyApplication()
				MyApp.Run(args)
			End Sub

		End Class
	End Namespace

End Namespace 'end of root namespace